# NumPy Array Concatenation Demo

In this notebook, I will demo **NumPy array concatenation**, which is the process of combining two or more arrays into one.

Function options include the `numpy.concatenate()` function or helper functions like `np.vstack()` (vertical stack) and `np.hstack()` (horizontal stack)
This is useful when working with datasets that need to be merged or when reshaping data for machine learning tasks.


In [2]:
import numpy as np

In [4]:
# We'll use two simple 1D arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

#Contatinate the arrays
concat_a_b = np.concatenate((a, b))
print(concat_a_b)

[1 2 3 4 5 6 7 8]


### Explanation
- `np.concatenate((a, b))` takes a tuple of arrays and joins them together.
- By default, it works along the first axis (axis=0).
- With 1D arrays, this just appends the second array to the first.


In [9]:
# Example with 2D arrays
x = np.array([[1,2],
             [3,4]])

y = np.array ([[5,6],
              [7,8]])

# Concatenate along rows (axis=0)
concat_xy_rows = np.concatenate((x,y), axis=0)
print("Concatenated rows:\n", concat_xy_rows)

concat_xy_columns = np.concatenate((x,y), axis=1)
print("Concatenated columns:\n",concat_xy_columns)

Concatenated rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated columns:
 [[1 2 5 6]
 [3 4 7 8]]


### How Axis Works
- **axis=0 (rows)**: stacks arrays on top of each other (more rows).
- **axis=1 (columns)**: stacks arrays side by side (more columns).

The arrays must have the same shape along the axis that is *not* being concatenated.
For example, if concatenating along rows, the number of columns must match.


In [11]:
# Vertical stack (same as axis=0)
vstack_result = np.vstack((x, y))
print("Vertical stack (vstack):\n", vstack_result)

# Horizontal stack (same as axis=1)
hstack_result = np.hstack((x, y))
print("Horizontal stack (hstack):\n", hstack_result)


Vertical stack (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack (hstack):
 [[1 2 5 6]
 [3 4 7 8]]


## Summary

- `np.concatenate()` combines arrays along a specified axis.
- `np.vstack()` and `np.hstack()` are convenient shortcuts for common cases.
- Concatenation is essential in tasks like **merging datasets, preparing training data**, or joining results after computations.

This is a simple but powerful tool for managing data structures in NumPy.
